[package]
name = "completers"
version = "0.1.0"
authors = ["SÅ‚awek Rudnicki <slawek.rudnicki@gmail.com>"]

[dependencies]
clap = "2.24.2"
itertools = "0.6.0"
libc = "0.2.23"
termion = "1.3.0"
termios = "0.2.2"

